version: '3'

services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://postgres:5432/postgres -schemas=public -user=postgres -password=postgres migrate
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql

